/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Jeanm
 */
public class BuscarProductosUsuario extends javax.swing.JFrame {

    /**
     * Creates new form BuscarProductosUsuario
     */
    public BuscarProductosUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Producto_head = new javax.swing.JLabel();
        nombreProductoUser = new javax.swing.JTextField();
        Producto_head1 = new javax.swing.JLabel();
        Producto_head2 = new javax.swing.JLabel();
        categoriaProductoUser = new javax.swing.JTextField();
        btn_buscarProducto = new javax.swing.JButton();
        Producto_head3 = new javax.swing.JLabel();
        nombreVendedorUser = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        Producto_head.setBackground(new java.awt.Color(255, 255, 255));
        Producto_head.setFont(new java.awt.Font("Muna", 1, 18)); // NOI18N
        Producto_head.setForeground(new java.awt.Color(0, 153, 255));
        Producto_head.setText("BUSCAR PRODUCTOS");

        nombreProductoUser.setText("Ingrese nombre del producto");
        nombreProductoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreProductoUserActionPerformed(evt);
            }
        });

        Producto_head1.setBackground(new java.awt.Color(255, 255, 255));
        Producto_head1.setFont(new java.awt.Font("Muna", 1, 13)); // NOI18N
        Producto_head1.setForeground(new java.awt.Color(102, 102, 102));
        Producto_head1.setText("Nombre del producto:");

        Producto_head2.setBackground(new java.awt.Color(255, 255, 255));
        Producto_head2.setFont(new java.awt.Font("Muna", 1, 13)); // NOI18N
        Producto_head2.setForeground(new java.awt.Color(102, 102, 102));
        Producto_head2.setText("Categoria:");

        categoriaProductoUser.setText("Ingrese categoria del producto");
        categoriaProductoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaProductoUserActionPerformed(evt);
            }
        });

        btn_buscarProducto.setBackground(new java.awt.Color(0, 153, 255));
        btn_buscarProducto.setFont(new java.awt.Font("Muna", 1, 13)); // NOI18N
        btn_buscarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btn_buscarProducto.setText("ENVIAR");
        btn_buscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarProductoActionPerformed(evt);
            }
        });

        Producto_head3.setBackground(new java.awt.Color(255, 255, 255));
        Producto_head3.setFont(new java.awt.Font("Muna", 1, 13)); // NOI18N
        Producto_head3.setForeground(new java.awt.Color(102, 102, 102));
        Producto_head3.setText("Nombre del vendedor:");

        nombreVendedorUser.setText("Ingrese nombre del vendedor");
        nombreVendedorUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreVendedorUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Producto_head1)
                    .addComponent(Producto_head2)
                    .addComponent(Producto_head3))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nombreVendedorUser)
                    .addComponent(categoriaProductoUser)
                    .addComponent(nombreProductoUser))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_buscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Producto_head)
                        .addGap(97, 97, 97))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(Producto_head)
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreProductoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Producto_head1))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoriaProductoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Producto_head2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreVendedorUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Producto_head3))
                .addGap(37, 37, 37)
                .addComponent(btn_buscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreProductoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreProductoUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreProductoUserActionPerformed

    private void categoriaProductoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaProductoUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoriaProductoUserActionPerformed

    private void btn_buscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_buscarProductoActionPerformed

    private void nombreVendedorUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreVendedorUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreVendedorUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarProductosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarProductosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarProductosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarProductosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarProductosUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Producto_head;
    private javax.swing.JLabel Producto_head1;
    private javax.swing.JLabel Producto_head2;
    private javax.swing.JLabel Producto_head3;
    private javax.swing.JButton btn_buscarProducto;
    private javax.swing.JTextField categoriaProductoUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombreProductoUser;
    private javax.swing.JTextField nombreVendedorUser;
    // End of variables declaration//GEN-END:variables
}
