/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author cristina
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        registro_heading = new javax.swing.JLabel();
        login_heading = new javax.swing.JLabel();
        lbl_login_usuario = new javax.swing.JLabel();
        lbl_login_pass = new javax.swing.JLabel();
        txt_registro_usuario = new javax.swing.JTextField();
        txt_login_pass = new javax.swing.JPasswordField();
        btn_registro = new javax.swing.JButton();
        lbl_registro_usuario = new javax.swing.JLabel();
        txt_login_usuario = new javax.swing.JTextField();
        lbl_registro_nombre = new javax.swing.JLabel();
        lbl_registro_cedula = new javax.swing.JLabel();
        lbl_registro_dob = new javax.swing.JLabel();
        lbl_registro_correo = new javax.swing.JLabel();
        lbl_registro_pass = new javax.swing.JLabel();
        lbl_registro_rol = new javax.swing.JLabel();
        txt_registro_correo = new javax.swing.JTextField();
        txt_registro_cedula = new javax.swing.JTextField();
        txt_registro_nombre = new javax.swing.JTextField();
        txt_registro_pass = new javax.swing.JPasswordField();
        rbtn_admin = new javax.swing.JRadioButton();
        rbtn_vendor = new javax.swing.JRadioButton();
        btn_login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        registro_heading.setBackground(new java.awt.Color(255, 255, 255));
        registro_heading.setFont(new java.awt.Font("Muna", 1, 18)); // NOI18N
        registro_heading.setForeground(new java.awt.Color(0, 153, 255));
        registro_heading.setText("REGISTRARSE");

        login_heading.setBackground(new java.awt.Color(255, 255, 255));
        login_heading.setFont(new java.awt.Font("Muna", 1, 18)); // NOI18N
        login_heading.setForeground(new java.awt.Color(0, 153, 255));
        login_heading.setText("INGRESAR");

        lbl_login_usuario.setFont(new java.awt.Font("Muna", 1, 13)); // NOI18N
        lbl_login_usuario.setForeground(new java.awt.Color(102, 102, 102));
        lbl_login_usuario.setText("USUARIO ");

        lbl_login_pass.setFont(new java.awt.Font("Muna", 1, 13)); // NOI18N
        lbl_login_pass.setForeground(new java.awt.Color(102, 102, 102));
        lbl_login_pass.setText("CONTRASEÑA ");

        txt_registro_usuario.setBackground(new java.awt.Color(255, 255, 255));
        txt_registro_usuario.setText(" Ingrese su nombre de usuario");
        txt_registro_usuario.setBorder(new javax.swing.border.MatteBorder(null));
        txt_registro_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_registro_usuarioActionPerformed(evt);
            }
        });

        txt_login_pass.setBackground(new java.awt.Color(255, 255, 255));
        txt_login_pass.setText("jPasswordField1");
        txt_login_pass.setBorder(new javax.swing.border.MatteBorder(null));

        btn_registro.setBackground(new java.awt.Color(0, 153, 255));
        btn_registro.setFont(new java.awt.Font("Muna", 1, 13)); // NOI18N
        btn_registro.setForeground(new java.awt.Color(255, 255, 255));
        btn_registro.setText("ENVIAR");
        btn_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registroActionPerformed(evt);
            }
        });

        lbl_registro_usuario.setFont(new java.awt.Font("Muna", 1, 13)); // NOI18N
        lbl_registro_usuario.setForeground(new java.awt.Color(102, 102, 102));
        lbl_registro_usuario.setText("USUARIO ");

        txt_login_usuario.setBackground(new java.awt.Color(255, 255, 255));
        txt_login_usuario.setText("Ingrese nombre de usuario");
        txt_login_usuario.setBorder(new javax.swing.border.MatteBorder(null));
        txt_login_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_login_usuarioActionPerformed(evt);
            }
        });

        lbl_registro_nombre.setFont(new java.awt.Font("Muna", 1, 13)); // NOI18N
        lbl_registro_nombre.setForeground(new java.awt.Color(102, 102, 102));
        lbl_registro_nombre.setText("NOMBRE");

        lbl_registro_cedula.setFont(new java.awt.Font("Muna", 1, 13)); // NOI18N
        lbl_registro_cedula.setForeground(new java.awt.Color(102, 102, 102));
        lbl_registro_cedula.setText("CEDULA");

        lbl_registro_dob.setFont(new java.awt.Font("Muna", 1, 13)); // NOI18N
        lbl_registro_dob.setForeground(new java.awt.Color(102, 102, 102));
        lbl_registro_dob.setText("FECHA DE NACIMIENTO");

        lbl_registro_correo.setFont(new java.awt.Font("Muna", 1, 13)); // NOI18N
        lbl_registro_correo.setForeground(new java.awt.Color(102, 102, 102));
        lbl_registro_correo.setText("CORREO");

        lbl_registro_pass.setFont(new java.awt.Font("Muna", 1, 13)); // NOI18N
        lbl_registro_pass.setForeground(new java.awt.Color(102, 102, 102));
        lbl_registro_pass.setText("CONTRASENA");

        lbl_registro_rol.setFont(new java.awt.Font("Muna", 1, 13)); // NOI18N
        lbl_registro_rol.setForeground(new java.awt.Color(102, 102, 102));
        lbl_registro_rol.setText("ACTIVIDAD");

        txt_registro_correo.setBackground(new java.awt.Color(255, 255, 255));
        txt_registro_correo.setText(" Ingrese su correo");
        txt_registro_correo.setBorder(new javax.swing.border.MatteBorder(null));
        txt_registro_correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_registro_correoActionPerformed(evt);
            }
        });

        txt_registro_cedula.setBackground(new java.awt.Color(255, 255, 255));
        txt_registro_cedula.setText(" Ingrese su cedula");
        txt_registro_cedula.setBorder(new javax.swing.border.MatteBorder(null));
        txt_registro_cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_registro_cedulaActionPerformed(evt);
            }
        });

        txt_registro_nombre.setBackground(new java.awt.Color(255, 255, 255));
        txt_registro_nombre.setText(" Ingrese su nombre");
        txt_registro_nombre.setBorder(new javax.swing.border.MatteBorder(null));
        txt_registro_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_registro_nombreActionPerformed(evt);
            }
        });

        txt_registro_pass.setBackground(new java.awt.Color(255, 255, 255));
        txt_registro_pass.setText("jPasswordField1");
        txt_registro_pass.setBorder(new javax.swing.border.MatteBorder(null));

        rbtn_admin.setBackground(new java.awt.Color(255, 255, 255));
        rbtn_admin.setText("Administrador");
        rbtn_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_adminActionPerformed(evt);
            }
        });

        rbtn_vendor.setBackground(new java.awt.Color(255, 255, 255));
        rbtn_vendor.setText("Vendedor");
        rbtn_vendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_vendorActionPerformed(evt);
            }
        });

        btn_login.setBackground(new java.awt.Color(0, 153, 255));
        btn_login.setFont(new java.awt.Font("Muna", 1, 13)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setText("ENVIAR");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_login_pass)
                    .addComponent(lbl_login_usuario)
                    .addComponent(lbl_registro_usuario)
                    .addComponent(lbl_registro_nombre)
                    .addComponent(lbl_registro_cedula)
                    .addComponent(lbl_registro_dob)
                    .addComponent(lbl_registro_correo)
                    .addComponent(lbl_registro_pass)
                    .addComponent(lbl_registro_rol))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(login_heading))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(registro_heading)
                                .addComponent(txt_login_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_registro_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_login_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_registro_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_registro_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_registro_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_registro_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(rbtn_admin)
                                    .addGap(18, 18, 18)
                                    .addComponent(rbtn_vendor)))
                            .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(login_heading)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_login_usuario)
                    .addComponent(txt_login_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_login_pass)
                    .addComponent(txt_login_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registro_heading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_registro_usuario)
                    .addComponent(txt_registro_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_registro_nombre)
                    .addComponent(txt_registro_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_registro_cedula)
                    .addComponent(txt_registro_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbl_registro_dob)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_registro_correo)
                    .addComponent(txt_registro_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_registro_pass)
                    .addComponent(txt_registro_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_registro_rol)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbtn_admin)
                        .addComponent(rbtn_vendor)))
                .addGap(18, 18, 18)
                .addComponent(btn_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_registro_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_registro_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_registro_usuarioActionPerformed

    private void btn_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_registroActionPerformed

    private void txt_login_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_login_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_login_usuarioActionPerformed

    private void txt_registro_correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_registro_correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_registro_correoActionPerformed

    private void txt_registro_cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_registro_cedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_registro_cedulaActionPerformed

    private void txt_registro_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_registro_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_registro_nombreActionPerformed

    private void rbtn_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_adminActionPerformed

    private void rbtn_vendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_vendorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_vendorActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null, "La informacion ingresada es" + txt_id.getText());
    }//GEN-LAST:event_btn_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_registro;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_login_pass;
    private javax.swing.JLabel lbl_login_usuario;
    private javax.swing.JLabel lbl_registro_cedula;
    private javax.swing.JLabel lbl_registro_correo;
    private javax.swing.JLabel lbl_registro_dob;
    private javax.swing.JLabel lbl_registro_nombre;
    private javax.swing.JLabel lbl_registro_pass;
    private javax.swing.JLabel lbl_registro_rol;
    private javax.swing.JLabel lbl_registro_usuario;
    private javax.swing.JLabel login_heading;
    private javax.swing.JRadioButton rbtn_admin;
    private javax.swing.JRadioButton rbtn_vendor;
    private javax.swing.JLabel registro_heading;
    private javax.swing.JPasswordField txt_login_pass;
    private javax.swing.JTextField txt_login_usuario;
    private javax.swing.JTextField txt_registro_cedula;
    private javax.swing.JTextField txt_registro_correo;
    private javax.swing.JTextField txt_registro_nombre;
    private javax.swing.JPasswordField txt_registro_pass;
    private javax.swing.JTextField txt_registro_usuario;
    // End of variables declaration//GEN-END:variables
}
