/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import View.VistaNuevaContrasena;
import javax.swing.JOptionPane;
import Modelo.Usuario;

/**
 *
 * @author cristina
 */
public class NuevaContrasena extends javax.swing.JFrame {

    /**
     * Creates new form NuevaContrasena
     */
    public NuevaContrasena() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pass_heading = new javax.swing.JLabel();
        btn_pass = new javax.swing.JButton();
        lbl_pass_oldpass = new javax.swing.JLabel();
        lbl_pass_newpass = new javax.swing.JLabel();
        lbl_pass_confirmpass = new javax.swing.JLabel();
        txt_pass_newpass = new javax.swing.JPasswordField();
        txt_pass_confirmpass = new javax.swing.JPasswordField();
        txt_pass_oldpass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        pass_heading.setBackground(new java.awt.Color(255, 255, 255));
        pass_heading.setFont(new java.awt.Font("Muna", 1, 18)); // NOI18N
        pass_heading.setForeground(new java.awt.Color(0, 153, 255));
        pass_heading.setText("REEMPLAZAR CONTRASEÑA");

        btn_pass.setBackground(new java.awt.Color(0, 153, 255));
        btn_pass.setFont(new java.awt.Font("Muna", 1, 13)); // NOI18N
        btn_pass.setForeground(new java.awt.Color(255, 255, 255));
        btn_pass.setText("ENVIAR");
        btn_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_passActionPerformed(evt);
            }
        });

        lbl_pass_oldpass.setFont(new java.awt.Font("Muna", 1, 13)); // NOI18N
        lbl_pass_oldpass.setForeground(new java.awt.Color(102, 102, 102));
        lbl_pass_oldpass.setText("Contraseña anterior:");

        lbl_pass_newpass.setFont(new java.awt.Font("Muna", 1, 13)); // NOI18N
        lbl_pass_newpass.setForeground(new java.awt.Color(102, 102, 102));
        lbl_pass_newpass.setText("Contraseña nueva:");

        lbl_pass_confirmpass.setFont(new java.awt.Font("Muna", 1, 13)); // NOI18N
        lbl_pass_confirmpass.setForeground(new java.awt.Color(102, 102, 102));
        lbl_pass_confirmpass.setText("Confirme contraseña nueva:");

        txt_pass_newpass.setBackground(new java.awt.Color(255, 255, 255));
        txt_pass_newpass.setText("jPasswordField1");
        txt_pass_newpass.setBorder(new javax.swing.border.MatteBorder(null));

        txt_pass_confirmpass.setBackground(new java.awt.Color(255, 255, 255));
        txt_pass_confirmpass.setText("jPasswordField1");
        txt_pass_confirmpass.setBorder(new javax.swing.border.MatteBorder(null));

        txt_pass_oldpass.setBackground(new java.awt.Color(255, 255, 255));
        txt_pass_oldpass.setText("jPasswordField1");
        txt_pass_oldpass.setBorder(new javax.swing.border.MatteBorder(null));
        txt_pass_oldpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pass_oldpassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(pass_heading))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_pass_confirmpass)
                                    .addComponent(lbl_pass_newpass, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_pass_oldpass, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_pass_newpass, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_pass_confirmpass, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_pass_oldpass, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(pass_heading)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_pass_oldpass)
                    .addComponent(txt_pass_oldpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_pass_newpass)
                            .addComponent(txt_pass_newpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(lbl_pass_confirmpass))
                    .addComponent(txt_pass_confirmpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btn_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_passActionPerformed
        // TODO add your handling code here:
        // Obtener las contraseñas ingresadas
        String oldPass = new String(txt_pass_oldpass.getPassword());
        String newPass = new String(txt_pass_newpass.getPassword());
        String confirmPass = new String(txt_pass_confirmpass.getPassword());

        // Validar si la contraseña nueva coincide con la confirmación
        if (!newPass.equals(confirmPass)) {
            JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
            return;
        }

        // Validar si la contraseña antigua coincide con la del usuario (esto se debería hacer con el usuario real)
        String contraseñaActual = new Usuario().getContrasena(); // Reemplazar con usuario autenticado
        if (!oldPass.equals(contraseñaActual)) {
            JOptionPane.showMessageDialog(null, "La contraseña actual no es correcta");
            return;
        }

        // Crear instancia de VistaNuevaContrasena y actualizar la contraseña
        VistaNuevaContrasena nuevaVista = new VistaNuevaContrasena();
        nuevaVista.setContraseña(newPass);

        JOptionPane.showMessageDialog(null, "Contraseña actualizada exitosamente");
    }//GEN-LAST:event_btn_passActionPerformed

    private void txt_pass_oldpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pass_oldpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pass_oldpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevaContrasena().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_pass;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_pass_confirmpass;
    private javax.swing.JLabel lbl_pass_newpass;
    private javax.swing.JLabel lbl_pass_oldpass;
    private javax.swing.JLabel pass_heading;
    private javax.swing.JPasswordField txt_pass_confirmpass;
    private javax.swing.JPasswordField txt_pass_newpass;
    private javax.swing.JPasswordField txt_pass_oldpass;
    // End of variables declaration//GEN-END:variables
}
