/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Jeanm
 */
public class RegistrarProducto extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarProducto
     */
    public RegistrarProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Producto_head = new javax.swing.JLabel();
        NombreProducto_field = new javax.swing.JTextField();
        Producto_head1 = new javax.swing.JLabel();
        Producto_head2 = new javax.swing.JLabel();
        precioProducto_field = new javax.swing.JTextField();
        Producto_head3 = new javax.swing.JLabel();
        descripcionProducto_field = new javax.swing.JTextField();
        Producto_head4 = new javax.swing.JLabel();
        cantidadProducto = new javax.swing.JTextField();
        btn_infoProducto = new javax.swing.JButton();
        Producto_head5 = new javax.swing.JLabel();
        Categoria = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        Producto_head.setBackground(new java.awt.Color(255, 255, 255));
        Producto_head.setFont(new java.awt.Font("Muna", 1, 18)); // NOI18N
        Producto_head.setForeground(new java.awt.Color(0, 153, 255));
        Producto_head.setText("REGISTRO DEL PRODUCTO");

        NombreProducto_field.setText("Ingrese nombre del producto");
        NombreProducto_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreProducto_fieldActionPerformed(evt);
            }
        });

        Producto_head1.setBackground(new java.awt.Color(255, 255, 255));
        Producto_head1.setFont(new java.awt.Font("Muna", 1, 13)); // NOI18N
        Producto_head1.setForeground(new java.awt.Color(102, 102, 102));
        Producto_head1.setText("Nombre del producto:");

        Producto_head2.setBackground(new java.awt.Color(255, 255, 255));
        Producto_head2.setFont(new java.awt.Font("Muna", 1, 13)); // NOI18N
        Producto_head2.setForeground(new java.awt.Color(102, 102, 102));
        Producto_head2.setText("Precio del producto:");

        precioProducto_field.setText("Ingrese precio del producto");
        precioProducto_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioProducto_fieldActionPerformed(evt);
            }
        });

        Producto_head3.setBackground(new java.awt.Color(255, 255, 255));
        Producto_head3.setFont(new java.awt.Font("Muna", 1, 13)); // NOI18N
        Producto_head3.setForeground(new java.awt.Color(102, 102, 102));
        Producto_head3.setText("Descripcion del producto:");

        descripcionProducto_field.setText("Ingrese una descripcion");
        descripcionProducto_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descripcionProducto_fieldActionPerformed(evt);
            }
        });

        Producto_head4.setBackground(new java.awt.Color(255, 255, 255));
        Producto_head4.setFont(new java.awt.Font("Muna", 1, 13)); // NOI18N
        Producto_head4.setForeground(new java.awt.Color(102, 102, 102));
        Producto_head4.setText("Cantidad del producto:");

        cantidadProducto.setText("Ingrese cantidad");
        cantidadProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadProductoActionPerformed(evt);
            }
        });

        btn_infoProducto.setBackground(new java.awt.Color(0, 153, 255));
        btn_infoProducto.setFont(new java.awt.Font("Muna", 1, 13)); // NOI18N
        btn_infoProducto.setForeground(new java.awt.Color(255, 255, 255));
        btn_infoProducto.setText("ENVIAR");
        btn_infoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_infoProductoActionPerformed(evt);
            }
        });

        Producto_head5.setBackground(new java.awt.Color(255, 255, 255));
        Producto_head5.setFont(new java.awt.Font("Muna", 1, 13)); // NOI18N
        Producto_head5.setForeground(new java.awt.Color(102, 102, 102));
        Producto_head5.setText("Categoria del producto:");

        Categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione categoria", "Alimentos frescos", "Lácteos y sus derivados", "Alimentos secos y enlatados", "Snacks y golosinas", "Bebidas", "Productos congelados", "Productos de limpieza", "Higiene personal", " " }));
        Categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Producto_head3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Producto_head4))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descripcionProducto_field)
                            .addComponent(cantidadProducto)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Producto_head1)
                            .addComponent(Producto_head2)
                            .addComponent(Producto_head5))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NombreProducto_field)
                            .addComponent(precioProducto_field)
                            .addComponent(Categoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_infoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Producto_head)
                        .addGap(89, 89, 89))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(Producto_head)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreProducto_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Producto_head1))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioProducto_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Producto_head2))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Producto_head5)
                    .addComponent(Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descripcionProducto_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Producto_head3))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Producto_head4))
                .addGap(34, 34, 34)
                .addComponent(btn_infoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreProducto_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreProducto_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreProducto_fieldActionPerformed

    private void precioProducto_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioProducto_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioProducto_fieldActionPerformed

    private void descripcionProducto_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descripcionProducto_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descripcionProducto_fieldActionPerformed

    private void cantidadProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadProductoActionPerformed

    private void btn_infoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_infoProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_infoProductoActionPerformed

    private void CategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Categoria;
    private javax.swing.JTextField NombreProducto_field;
    private javax.swing.JLabel Producto_head;
    private javax.swing.JLabel Producto_head1;
    private javax.swing.JLabel Producto_head2;
    private javax.swing.JLabel Producto_head3;
    private javax.swing.JLabel Producto_head4;
    private javax.swing.JLabel Producto_head5;
    private javax.swing.JButton btn_infoProducto;
    private javax.swing.JTextField cantidadProducto;
    private javax.swing.JTextField descripcionProducto_field;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField precioProducto_field;
    // End of variables declaration//GEN-END:variables
}
